task:
  name: MacOS
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  test_script:
    - curl -L https://install.perlbrew.pl | bash
    - source ~/perl5/perlbrew/etc/bashrc
    - perlbrew init
    - perlbrew install -v perl-5.30.3
    - perlbrew switch perl-5.30.3
    - perlbrew install-cpanm -f
    - perl -v
    - cpanm TAP::Harness::Env
    - cpanm --installdeps . || cat /Users/admin/.cpanm/work/*/build.log
    - perl Makefile.PL
    - make
    - make test
